source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'DataStoreKit_Example' do
  pod "DataStoreKit", :path => "../"
end

target 'DataStoreKit_Tests' do
  pod "DataStoreKit", :path => "../"

  
end
