source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'DataStoreKit_Example', :exclusive => true do
  pod "DataStoreKit", :path => "../"
end

target 'DataStoreKit_Tests', :exclusive => true do
  pod "DataStoreKit", :path => "../"

  
end
